#ifndef __INPUT_KEYS_HPP__
#define __INPUT_KEYS_HPP__
enum INPUT_KEY
{ 
	INPUT_KEY_RETURN			= 8,
	INPUT_KEY_RETURN_WINDOWS	= 8,
	INPUT_KEY_RETURN_LINUX		= 263,
	INPUT_KEY_ENTER				= 10,
	INPUT_ARROW_KEY_DOWN		= 258,
	INPUT_ARROW_KEY_UP			= 259,
	INPUT_ARROW_KEY_LEFT		= 260,
	INPUT_ARROW_KEY_RIGHT		= 261
};
#endif // !__INPUT_KEYS_HPP__
