#ifndef __FILE_DATA_POSITIONS_HPP__
#define __FILE_DATA_POSITIONS_HPP__
enum FILE_DATA_POSITIONS
{
	FILE_DATA_CONTROLLER_TICKRATE = 0,
	FILE_DATA_TMP36_TICKRATE = 2,
	FILE_DATA_SMSM_TICKRATE = 4,
	FILE_DATA_VALVE_OPEN_VALUE = 6,
	FILE_DATA_VALVE_CLOSE_VALUE = 8
};
#endif // !__FILE_DATA_POSITIONS_HPP__
